# Generated by Django 4.0.1 on 2022-01-28 15:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_usertaskreportsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskreportsetting',
            name='report_time',
            field=models.TimeField(default=datetime.time(15, 0, 26, 440965)),
        ),
        migrations.AlterField(
            model_name='usertaskreportsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
