# Generated by Django 4.0.1 on 2022-01-28 15:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_usertaskreportsetting_report_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskreportsetting',
            name='report_time',
            field=models.TimeField(default=datetime.datetime(2022, 1, 28, 15, 0, 37, 523591, tzinfo=utc)),
        ),
    ]
