# Generated by Django 4.0.1 on 2022-01-29 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_usertaskreportsetting_report_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskreportsetting',
            name='report_time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
