# Generated by Django 4.0.1 on 2022-01-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_usertaskreportsetting_report_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='taskhistory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='taskhistory',
            name='version',
        ),
    ]
