# Generated by Django 4.0.1 on 2022-02-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_taskhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskreportsetting',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
