# Generated by Django 4.0.1 on 2022-02-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_usertaskreportsetting_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskreportsetting',
            name='last_sent_at',
            field=models.DateTimeField(),
        ),
    ]
